### ISSUE TITLE
 It doesn't block where it should  It blocks where it shouldn't

### ISSUE THREAD

**Issue by kangarooo** [RomanistHere/PopUpOFF#32]
Something missing- options can select full productivity, then works on [www.tvnet.lv](https://www.tvnet.lv/) but it blocks some releted stories to right too off in https://www.thelocal.fr/20221210/frances-mediawan-buys-majority-stake-in-brad-pitts-plan-b/
So not ideal for every site

**Comment by RomanistHere** [comment]
Thanks for the feedback, I'm watching and checking how the extension works on different websites and improving it accordingly.

On this link you shared, for example (https://www.thelocal.fr/20221210/frances-mediawan-buys-majority-stake-in-brad-pitts-plan-b), PopUpOFF is able to show the content otherwise hidden behing a paywall for free. So it does more than just remove annoyances, but also let's you bypass paying website and saves you money.
